### ISSUE TITLE
can't make it run properly on my mac

### ISSUE THREAD

**Issue by SydOps** [paluh/ansible-augeas#20]
I have installed augeas via `brew install augeas`. 

Not sure how to install `augeas python bindings`, any help?
```
"msg": "Could not import python augeas module. Please install augeas related packages and augeas python bindings."}
```

**Comment by paluh** [comment]
I really can't help you as I don't use `brew`. Could you check if there is anything like `python-augeas`? If you don't have system package which contains this python bindings, you can try to install it through `pip`, (probably the best way is to install it in python `virtualenv` to not pollute global python package space) .

**Comment by SydOps** [comment]
Finally, got the problem fixed. The python module `augeas` need be installed at client with below code in ansible playbook

```
- easy_install: name=pip state=latest
- pip: name=python-augeas
```

Thinking to update this repository's README for easy understanding.
