### ISSUE TITLE
Mark as changed always

### ISSUE THREAD

**Issue by SydOps** [paluh/ansible-augeas#22]
Thanks to write the useful tool for Ansible users. But I found an issue.

Every run, the task with `ansible-augeas` is marked as `changed`. Since the task notifies a `sshd` service restart, then sshd service get restart every time. 

The task for your reference. 

```
- action: augeas commands='set /files/etc/ssh/sshd_confi/AuthorizedKeysCommand /usr/bin/sss_ssh_authorizedkeys
                           set /files/etc/ssh/sshd_confi/AuthorizedKeysCommandUser nobody'
  notify:
    - restart sshd
```

**Comment by ksyz** [comment]
Same case here. But, looking at inside the module There is probably no direct way to say, if augeas did change anything. It calls [Augeas.set](/paluh/ansible-augeas/blob/master/library/augeas.py#L397), and that is jsut a layer for [libaugeas.aug_set](/hercules-team/python-augeas/blob/master/augeas.py#L185), which according to [docs](http://augeas.net/docs/api.html), only returns 0 or -1.

Using temporary file and do a diff may do the job, though.

**Comment by paluh** [comment]
It seems that there is a way to check which files are modified by augeas:

https://github.com/hercules-team/augeas/wiki/Change-how-files-are-saved#finding-out-what-files-were-modified

To be honest currently I don't have time to improve/fix this situation, so I can't promise when it will land in this module.

**Comment by ksyz** [comment]
OK, great hint! These are my 50 cents, actually learned this much of python while having lunch.

**Comment by paluh** [comment]
Thanks again @ksyz!
