### ISSUE TITLE
Cut a tag?

### ISSUE THREAD

**Issue by jtreminio** [paluh/ansible-augeas#26]
Would you mind cutting a tag? Doesn't have to be 1.0 if you don't think this role is stable yet, but would prefer a tag vs having to point to `0f4dc1bac2e5f595e8cdb38015687fc4b86f231f`.

**Comment by paluh** [comment]
I've tagged it v1.0.0, but I'm not sure if this is correct version format for ansible roles (In Galaxy documentation there are numerous examples with different formats). What do you think?
