### ISSUE TITLE
ansible-doc gives TypeError for requirements

### ISSUE THREAD

**Issue by MatthewHannigan** [paluh/ansible-augeas#6]
ansible-doc (v1.8.2) gives an exception ending in ```TypeError: sequence iterm 1: expected string, dict found```

[This line](https://github.com/paluh/ansible-augeas/blob/master/augeas#L32) needs to be quoted because of the colon after "note".  i.e.

      - "augeas python bindings (python-augeas on Debian, note: on Debian Wheezy you also need to install libpython2.7, since python-augeas package wrongly does not list it as a requirement)"

**Comment by paluh** [comment]
Thanks for reporting! Fixed!
