### ISSUE TITLE
support for ins

### ISSUE THREAD

**Issue by drzraf** [paluh/ansible-augeas#7]
ins is very useful, especially with ```commands```, eg:
```
      ins selector after /files/etc/rsyslog.conf/entry[action/file=\"/var/log/syslog\"]/selector[last()]     
      set /files/etc/rsyslog.conf/entry[action/file="/var/log/syslog"]/selector[last()]/facility local0      
      set /files/etc/rsyslog.conf/entry[action/file="/var/log/syslog"]/selector[last()]/level none
```
would keep local0 from being logged into syslog.
It's clearly not idempotent (inserting many time the same node is possible, but in the rsyslog case, it does not have side effect other than cluttering the rc file uselessly, but that's up to the user to check this)

This can't be achieved without Augeas **ins**, since relying on **set** for a non-existent path will insert the node not only after the last selector, but after the "action" (which are siblings) what will fail to be parsed and saved.

This patch did the trick:

```diff
diff --git a/playbooks/library/augeas b/playbooks/library/augeas
index 48a650f..c1ec9e3 100644
--- a/playbooks/library/augeas
+++ b/playbooks/library/augeas
@@ -212,6 +212,7 @@ def parse_commands(commands):
         'set': ['path', 'value'],
         'rm': ['path'],
         'match': ['path'],
+        'ins': ['label', 'where', 'path'],
     }
     try:
         tokens = iter(shlex.split(commands, comments=False))
@@ -315,6 +316,15 @@ def execute(augeas_instance, commands):
                 result = changed = True
             else:
                 result = False
+        elif command == 'ins':
+            path = params['path']
+            label = params['label']
+            where = params['where']
+            if augeas_instance.insert(path, label, where == 'before'):
+                augeas_instance.remove(path)
+                result = changed = True
+            else:
+                result = False
         else: # match
             result = [{'label': s, 'value': augeas_instance.get(s)} for s in augeas_instance.match(**params)]
         results.append((command + ' ' + ' '.join(p if p else '""' for p in params.values()), result))

**Comment by paluh** [comment]
Hi,

I really want to merge your proposition.  I can missing the point, but I just want to be sure that our `ins` command strictly follows semantics of original `augeas` `ins` - could you explain why there is `remove` call after `insert` execution in your patch?

**Comment by drzraf** [comment]
The only explanation I can come up with is that ... it comes from a bad copy/paste and should not be here! sorry about that, you can just strip this line! I wonder how I didn't noticed it during my various uses.

About ```match``` before action, it's not relevant for the _ins_ command
About ```changed```, the patch could be better because the ```else:``` will never be reached.
```/usr/lib/python2.7/dist-packages/augeas.py``` shows that if the call to
```python,
Augeas._libaugeas.aug_insert(self.__handle, path, label, before and 1 or 0)
```
returns something other than **0**, it will:
```python
raise ValueError("Unable to insert label!")
```

The _ins_ command is hardly testable ourselves (in case it's needed unless augeas provides all the stuff needed to test a command is valid, and whether or not it would affect a node).

**Comment by paluh** [comment]
I've added `ins` to the module according to your suggestions. I've also added you to AUTHORS file - I hope it's not a problem for you. Thanks, a lot for your contributions!
