### ISSUE TITLE
Does the module support setting the lens manually?

### ISSUE THREAD

**Issue by adamryczkowski** [paluh/ansible-augeas#8]
I wonder, if the module supports manual lens loading? I want to port the following command:

`augtool -L -A --transform "Shellvars incl /etc/default/lxc-net" set "/files/etc/default/lxc-net/LXC_BRIDGE" $internalif`

into Ansible with your module.

For the reference, this is how I would do that in Puppet:
```puppet
  augeas { "Change lxc_bridge interface":
    incl    => "/etc/default/lxc-net",
    lens    => 'Shellvars.lns',
    onlyif  => "get LXC_BRIDGE != ${internalif}",
    changes => "set LXC_BRIDGE ${internalif}",
    require => Package['lxc']
  }
```

**Comment by paluh** [comment]
Unfortunately, it is impossible to change `/augeas/load` state in the current version. There are only `root` and `loadpath` vars, but you can`t assign arbitrary lens to process a file with these settings.

`python-augeas` binding (which is used in `ansible-augeas` module) provides `transform` and `add_transform` methods, but there are not supported by the current version of `ansible-augeas` module:

https://github.com/hercules-team/python-augeas/blob/master/augeas.py#L547
https://github.com/hercules-team/python-augeas/blob/master/augeas.py#L570

Could you check whether those methods are what you are looking for?  I can provide support for them but I'm afraid that you have to wait for such a changes one or two weeks (I have some urgent work to finish - "deadline is coming" ;-)).

**Comment by paluh** [comment]
I've added support for `transform` command. It undocumented and parameters validation is not implemented, but it works. I've tested it against:

    - hosts: localhost
                 sudo: True
      tasks:
        - name: Add user to allowed users
          action: augeas commands='transform "sshd" "incl" "/home/paluh/programming/ansible/home/sshd_config"
                                   set "/files/home/paluh/programming/ansible/home/sshd_config/ForwardAgent" "yes"'


It is strange but when I tested `transform` functionality in `augtool` (I've never used it before) I've noticed that `match` and `ins` don't work on newly included files, but `set` command works correctly. I'm not sure why - do you have any idea?

**Comment by paluh** [comment]
Ok, I've found that after every `transform` I have to call `load` internally to make `match` and `ins` work properly.

**Comment by adamryczkowski** [comment]
The `augeas: commands='transform "Shellvars" "incl" "/<bash filepath>" set "/files/<the same filepath>/<key>" "<value>"'` works perfectly for me. Thank you very much!!
