### ISSUE TITLE
Example on ins command

### ISSUE THREAD

**Issue by javiplx** [paluh/ansible-augeas#9]
I'm not able to insert an item. It should be possible to add some explicit documentation about it?

**Comment by paluh** [comment]
I've added example for `ins` command (it is one before last example).

I think that `ins` command has only sens when it is used in bulk mode (when command="commands"), but I can be wrong - I've added it from pull request and never really used in my projects ;-).  In case of bulk execution order of parameters to the command is important and it follows original augeas syntax: `ins label where path`
